name: main pull request
on:
  push:
    branches:
      - api
jobs:
  Pulling:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main