name: beta pull request
on:
  push:
    branches:
      - beta
jobs:
  autoPull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: autoPull from beta
          title: autoPull from beta
          body: autoPull from beta
          branch: main
          base: beta